networks:
  slack-search-net:
    driver: bridge

volumes:
  es-data:
    driver: local
  frontend-static:

services:
  elasticsearch:
    build:
        context: ./elastic
        dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - slack-search-net
    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
      interval: 10s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - type: volume
        source: frontend-static
        target: /app/build
        read_only: true
      - type: bind
        source: ./archive
        target: /archive
        read_only: true
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    networks:
      - slack-search-net
    depends_on:
      - elasticsearch
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 5
    user: "nobody"

  nginx:
    image: nginxinc/nginx-unprivileged:1.25-alpine
    container_name: nginx-slack
    ports:
      - "127.0.0.1:8000:8000"
      - "[::1]:8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./archive:/var/www/archive:ro
      - frontend-static:/var/www/react-build:ro
    networks:
      - slack-search-net
    depends_on:
      - frontend
    restart: always
    user: "nobody"

  indexer:
    profiles: ["index"]
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
      - slack-search-net
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./archive:/app/archive

